spring:
  profiles:
    default: local
  web:
    resources:
      add-mappings: 'false'
    mvc:
      throw-exception-if-no-handler-found: 'true'

  datasource:
    url: jdbc:mariadb://localhost:3306/dogfight
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: kim15413

  jpa:
    hibernate:
      ddl-auto: none

  jwt:
    key: do-you-like-fighting
    live:
      access-expiration-time: 4320
      refresh-expiration-time: 1209600

  data:
    redis:
      host: redis
      port: 6379
---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate ??? ?? data.sql ??

  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never